webappbloom/Models/Competencia.cs
namespace WebAppBloom.Models;
public class Competencia // Camada Model
{
    public int Id  { get; set; }
    public string? ColunaBloom { get; set; } // a partir do dotnet 6? ,  nao permitido valores nulos para a variavel quando é declarada como objeto (string é uma classe), por isso o "?" para não precisar atribuir valores para o objeto não criação.
    public string? LinhaBloom { get; set; }
}

webappbloom/ViewModels/DetalhesCompViewModel.cs
using WebAppBloom.Models;

namespace WebAppBloom.ViewModels;

public class DetalhesCompViewModel{

    public Competencia? Competencia {get;set;}
    public string TituloPagina { get; set; } = string.Empty;
    
}

webappbloom/ViewModels/ListaCompetenciaViewModel.cs
using WebAppBloom.Models;

public class ListaCompetenciaViewModel{

    public ICollection<Competencia> Competencias {get; set;} = new List<Competencia>(); // ou colocar "<>?" para nao precisar atribuir um valor
    
}

webappbloom/Controllers/CompetenciaController.cs
using Microsoft.AspNetCore.Mvc;
// controller/action/opcionais
// classe é u conjunto de objetos
// metodo é uma função
// ações são métodos, cada action representa uma página
using WebAppBloom.Models;
using WebAppBloom.ViewModels;
using WebAppBloom.Contexts;

namespace WebAppBloom.Controllers;
public class CompetenciaController : Controller{
    
    private readonly AppDbConext _context; // variavel para a conexão com o banco de dados
    
    public CompetenciaController(AppDbConext context) // poderiamos utilizar a instanciação de objetos aqui. Com injeção de dependencias, o framework fica responsável pela instanciação
    {
        _context = context;
    }
    public IActionResult Index(){ // O nome do arquivo deve ser igual ao da Action, Index() nesse caso retorna a View do Index.cshtml em Competencia
    
        Competencia competencia = new Competencia();
        competencia.ColunaBloom = "MEMORIZAR";
        competencia.LinhaBloom = "Listar";

        ViewData["titulo"] = "Compreender o funcionamento do Razor";
        ViewData["tablebloom"] = competencia;

        return View();
    }
    public IActionResult RelatorioComp(){
       
        var competencias = _context.Competencias.ToList();
        return View();

        // var competencia = new Competencia(){
        //    ColunaBloom = "Teste Coluna",
        //    LinhaBloom = "Teste Linha", 
        // };
        // var viewModel = new DetalhesCompViewModel(){
        //     Competencia = competencia,
        //     TituloPagina = "Página de Teste",
        // };
        //return View(viewModel);    
    }
    public IActionResult Listar(){
        var listaCompe = _context.Competencias.ToList();
        var listaViewModel = new ListaCompetenciaViewModel{
            Competencias = listaCompe
        };

        return View(listaViewModel);
    }
}

// LAB-F08-24

webappbloom/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace WebAppBloom.Controllers;
public class HomeController : Controller 
{
    public IActionResult Index()
    {
        return View(); // 3 sobrecargas. 3 formas de passar parametros
    }
}

webappbloom/Views/Competencia/Index.cshtml
@* 
<p>Competência</p> @ViewData["titulo"]

@{
    var competencia = ViewData["tablebloom"] as Competencia; //Declarado como tipo Competencia, ViewData precisa enfatizar o tipo
} *@

<div class="text-Left">
    <h1>Taxonomia de Bloom</h1>
    <p></p>
<form>
<div class="container">
  <div class="row row-cols-auto">
    <div class="col">
      @* <input type = "text"> *@
      <div class="input-group mb-3">
        <span class="input-group-text" id="inputGroup-sizing-default">Competência</span>
        <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
      </div>
    </div>
    <div class="col">
      <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                    Selecione o Verbo
                  </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                    <li><a class="dropdown-item" href="#">Memorizar</a></li>
                    <li><a class="dropdown-item" href="#">Compreender</a></li>
                    <li><a class="dropdown-item" href="#">Aplicar</a></li>
                    <li><a class="dropdown-item" href="#">Analisar</a></li>
                    <li><a class="dropdown-item" href="#">Avaliar</a></li>
                    <li><a class="dropdown-item" href="#">Criar</a></li>
                  </ul>
      </div>
    </div>
    <div class="col">
      <button type="button" class="btn btn-primary">Cadastrar</button>
    </div>
  </div>
</div>
</form>

webappbloom/Views/Competencia/Listar.cshtml
@model ListaCompetenciaViewModel
<h1>Listando Competências</h1>

<table class="table">
  <thead>
    <tr>
      @{
        Dictionary<string, List<string>> competencias = new Dictionary<string, List<string>>()
        {
            {"MEMORIZAR", new List<string>()},
            {"COMPREENDER", new List<string>()},
            {"APLICAR", new List<string>()},
            {"ANALISAR", new List<string>()},
            {"AVALIAR", new List<string>()},
            {"CRIAR", new List<string>()},
        };

        foreach(var item in Model.Competencias)
        {
            foreach(string key in competencias.Keys)
            {
                if(@item.ColunaBloom?.ToString().ToUpper() == key){competencias[key].Add(@item.LinhaBloom);}
            }
        }
        foreach (string key in competencias.Keys){
            <th scope="col">@key</th>
        };
      }
    </tr>
  </thead>
  <tbody>
    <tbody>
        @{
            for (int i = 0; i < competencias.Values.Count; i++)
            {
                <tr>
                @foreach(string key in competencias.Keys)
                {
                    try{
                        <td>@competencias[key][i]</td>
                    }
                    catch{}
                }
                </tr>
            }
        }
  </tbody>
</table>

webappbloom/Views/Competencia/RelatorioComp.cshtml
@model DetalhesCompViewModel;

<h1>@Model.TituloPagina</h1>

webappbloom/Views/Home/Index.cshtml
<h1>Taxonomia de Bloom</h1>

webappbloom/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - webappbloom</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/webappbloom.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">webappbloom</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Competencia" asp-action="Index">Competência</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Competencia" asp-action="Listar">Listar Competências</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - webappbloom - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>